from __future__ import annotations

import base64
import json
from typing import Any

import httpx

from app.config import settings
from app.core.exceptions import AppException
from app.core.logging import get_logger

logger = get_logger(__name__)


class GitHubService:
    """Push generated projects to GitHub repositories."""

    API_BASE = "https://api.github.com"

    def __init__(self) -> None:
        self.token = settings.GITHUB_TOKEN or ""
        self.default_owner = settings.GITHUB_OWNER or ""

    @property
    def _headers(self) -> dict[str, str]:
        return {
            "Authorization": f"Bearer {self.token}",
            "Accept": "application/vnd.github+json",
            "User-Agent": "ai-software-development-team/1.0",
        }

    async def _request(
        self,
        method: str,
        path: str,
        **kwargs: Any,
    ) -> httpx.Response:
        url = f"{self.API_BASE}{path}"
        async with httpx.AsyncClient() as client:
            response = await client.request(
                method, url, headers=self._headers, **kwargs
            )
        return response

    async def create_repository(
        self,
        name: str,
        organization: str | None = None,
        private: bool = False,
        description: str = "",
    ) -> dict[str, Any]:
        """Create a GitHub repository.

        Returns the repository data from the GitHub API.
        """
        owner = organization or self.default_owner
        path = f"/orgs/{owner}/repos" if owner and organization else "/user/repos"

        payload: dict[str, Any] = {
            "name": name,
            "private": private,
            "description": description or "Generated by AI Software Development Team",
            "auto_init": True,
        }

        response = await self._request("POST", path, json=payload)

        if response.status_code == 201:
            repo = response.json()
            logger.info(
                "github_repo_created",
                repo=repo.get("full_name"),
                url=repo.get("html_url"),
            )
            return repo

        if response.status_code == 422:
            errors = response.json().get("errors", [])
            if any(e.get("message", "").startswith("name already exists") for e in errors):
                # Repository already exists — fetch it
                login = response.json().get("owner", {}).get("login", "")
                existing_path = f"/repos/{owner or login}/{name}"
                existing = await self._request("GET", existing_path)
                if existing.status_code == 200:
                    logger.info("github_repo_exists", repo=name)
                    return existing.json()

        raise AppException(
            message=f"Failed to create repository: {response.status_code}",
            status_code=502,
            details={"response": response.text[:500]},
        )

    async def push_file(
        self,
        owner: str,
        repo: str,
        path: str,
        content: str,
        message: str = "Add generated file",
        sha: str | None = None,
    ) -> dict[str, Any]:
        """Create or update a file in the repository."""
        encoded = base64.b64encode(content.encode()).decode()
        payload: dict[str, Any] = {
            "message": message,
            "content": encoded,
        }
        if sha:
            payload["sha"] = sha

        url = f"/repos/{owner}/{repo}/contents/{path}"
        response = await self._request("PUT", url, json=payload)

        if response.status_code in (200, 201):
            return response.json()

        raise AppException(
            message=f"Failed to push file {path}: {response.status_code}",
            status_code=502,
            details={"response": response.text[:500]},
        )

    async def get_file_sha(
        self, owner: str, repo: str, path: str
    ) -> str | None:
        """Get the SHA of an existing file (needed for updates)."""
        url = f"/repos/{owner}/{repo}/contents/{path}"
        response = await self._request("GET", url)
        if response.status_code == 200:
            return response.json().get("sha")
        return None

    async def export_project(
        self,
        project_id: str,
        project_data: dict[str, Any],
        repo_name: str,
        organization: str | None = None,
        private: bool = False,
    ) -> dict[str, Any]:
        """Export a generated project to GitHub.

        Creates a repository (if needed) and pushes all generated
        artifacts as files.
        """
        if not self.token:
            raise AppException(
                message="GitHub token not configured. Set GITHUB_TOKEN in environment.",
                status_code=502,
            )

        description = project_data.get("requirements", {}).get(
            "project_overview", ""
        ) or f"AI-generated project: {project_id}"

        repo = await self.create_repository(
            name=repo_name,
            organization=organization,
            private=private,
            description=description[:200],
        )

        full_name = repo["full_name"]
        owner, repo_name_only = full_name.split("/", 1)

        # Collect files to push
        files: list[tuple[str, str, str]] = []

        # README
        readme = "# " + repo_name + "\n\n"
        readme += (project_data.get("documentation", {}) or {}).get(
            "readme", ""
        ) or description
        files.append(("README.md", readme, "Add README"))

        # Requirements artifact
        reqs = project_data.get("requirements")
        if reqs:
            files.append(
                ("docs/requirements.json", json.dumps(reqs, indent=2), "Add requirements")
            )

        # Architecture artifact
        arch = project_data.get("architecture")
        if arch:
            files.append(
                ("docs/architecture.json", json.dumps(arch, indent=2), "Add architecture")
            )

        # Source code
        source = project_data.get("source_code")
        if source and isinstance(source, dict):
            source_files = source.get("files", [])
            for sf in source_files:
                file_path = sf.get("path", "")
                content = sf.get("content", "")
                if file_path and content:
                    files.append((file_path, content, "Add source code"))

        # Test suite
        tests = project_data.get("test_suite")
        if tests and isinstance(tests, dict):
            test_files = tests.get("files", [])
            for tf in test_files:
                file_path = tf.get("file_path", "") or tf.get("path", "")
                content = tf.get("code", "") or tf.get("content", "")
                if file_path and content:
                    files.append((file_path, content, "Add tests"))

        # Documentation
        docs = project_data.get("documentation")
        if docs and isinstance(docs, dict):
            setup_guide = docs.get("setup_guide", "")
            if setup_guide:
                files.append(
                    ("docs/SETUP.md", setup_guide, "Add setup guide")
                )

        # Push all files
        pushed = []
        for file_path, content, commit_message in files:
            try:
                result = await self.push_file(
                    owner, repo_name_only, file_path, content, commit_message
                )
                content_sha = result.get("content", {}).get("sha", "")
                pushed.append(
                    {"path": file_path, "status": "created", "sha": content_sha}
                )
            except AppException as exc:
                logger.warning(
                    "github_push_skipped",
                    path=file_path,
                    error=str(exc),
                )
                pushed.append({"path": file_path, "status": "skipped"})

        repo_url = repo.get("html_url", f"https://github.com/{full_name}")
        logger.info(
            "github_export_complete",
            project_id=project_id,
            repo=full_name,
            files_pushed=len(pushed),
        )

        return {
            "repository": full_name,
            "url": repo_url,
            "files_pushed": len(pushed),
            "files": pushed,
        }


github_service = GitHubService()
